

welcomemsg: Hello


outofworkinghoursexperience:
  timeValueList:
    - locale: ja_jp,
      timezone: JST,
      startTime: 9:30,
      endTime: 18:00
    - locale: ka_KP,
      timezone: KST,
      startTime: 9:30,
      endTime: 18:00

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"

